In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Emotion_classify_Data.csv')
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

# **Text-Cleaning**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5937 entries, 0 to 5936
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Comment  5937 non-null   object
 1   Emotion  5937 non-null   object
dtypes: object(2)
memory usage: 92.9+ KB

In [ ]:
df.describe()

                                                  Comment Emotion
count                                                5937    5937
unique                                               5934       3
top     i feel pretty tortured because i work a job an...   anger
freq                                                    2    2000

In [ ]:
df.isnull().sum()

Comment    0
Emotion    0
dtype: int64

In [ ]:
df['Emotion'].unique()

array(['fear', 'anger', 'joy'], dtype=object)

In [ ]:
e_number = {}
i = 0
for e in df['Emotion'].unique():
    e_number[e] = i
    i += 1
df['Emotion'] = df['Emotion'].map(e_number)

In [ ]:
df

                                                Comment  Emotion
0     i seriously hate one subject to death but now ...        0
1                    im so full of life i feel appalled        1
2     i sit here to write i start to dig out my feel...        0
3     ive been really angry with r and i feel like a...        2
4     i feel suspicious if there is no one outside l...        0
...                                                 ...      ...
5932                 i begun to feel distressed for you        0
5933  i left feeling annoyed and angry thinking that...        1
5934  i were to ever get married i d have everything...        2
5935  i feel reluctant in applying there because i w...        0
5936  i just wanted to apologize to you because i fe...        1

[5937 rows x 2 columns]

LowerCaseing

In [ ]:
df['Comment'] = df['Comment'].apply(lambda x: x.lower())
df

                                                Comment  Emotion
0     i seriously hate one subject to death but now ...        0
1                    im so full of life i feel appalled        1
2     i sit here to write i start to dig out my feel...        0
3     ive been really angry with r and i feel like a...        2
4     i feel suspicious if there is no one outside l...        0
...                                                 ...      ...
5932                 i begun to feel distressed for you        0
5933  i left feeling annoyed and angry thinking that...        1
5934  i were to ever get married i d have everything...        2
5935  i feel reluctant in applying there because i w...        0
5936  i just wanted to apologize to you because i fe...        1

[5937 rows x 2 columns]

Remove Punctuations

In [ ]:
import string
def remove_punctuation(txt):
  return txt.translate(str.maketrans('','',string.punctuation))
df['Comment'].apply(remove_punctuation)

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Numbers

In [ ]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new
df['Comment'].apply(remove_number)

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove URL

In [ ]:
import re
def remove_url(txt):
  new = "https?://\S+|www\.\S+"

  remove = re.sub(new,'',str(txt))
  return remove.strip()
df['Comment'] = df['Comment'].apply(remove_url)
df['Comment']

<>:3: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_188/959417279.py:3: SyntaxWarning: invalid escape sequence '\S'
  new = "https?://\S+|www\.\S+"

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove HTML Tags

In [ ]:
def remove_tag(txt):
  new = r"<.*?>"

  remove = re.sub(new,'',str(txt))
  return remove.strip()
df['Comment'] = df['Comment'].apply(remove_tag)
df['Comment']

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Special Characters & Emojis

In [ ]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new
df['Comment'] = df['Comment'].apply(remove_emojis)
df['Comment']

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Stopwords

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
nltk.download('punkt_tab')
def remove_stopwords(txt):
  word = word_tokenize(txt)
  cleaned = []
  for i in word:
    if i not in stopwords:
      cleaned.append(i)
  return ' '.join(cleaned)
df['Comment'] = df['Comment'].apply(remove_stopwords)
df.loc[1]['Comment']

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

'im full life feel appalled'

Spelling check

In [ ]:
from textblob import TextBlob
def correct_spell(txt):
  return str(TextBlob(txt).correct())

In [ ]:
df

                                                Comment  Emotion
0     seriously hate one subject death feel reluctan...        0
1                            im full life feel appalled        1
2     sit write start dig feelings think afraid acce...        0
3     ive really angry r feel like idiot trusting fi...        2
4     feel suspicious one outside like rapture happe...        0
...                                                 ...      ...
5932                              begun feel distressed        0
5933  left feeling annoyed angry thinking center stu...        1
5934  ever get married everything ready offer got to...        2
5935  feel reluctant applying want able find company...        0
5936         wanted apologize feel like heartless bitch        1

[5937 rows x 2 columns]

# **Model spliting**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df['Comment'],df['Emotion'], test_size=0.20, random_state=42)

In [ ]:
x_train

4945    remember day phone fri shannon telling cried f...
5428    go gym many times last spring kind got used fe...
1344    feel irritated either interrupts quiet time wakes
1888    really hate feeling really give much damn some...
2480                           left feeling little shaken
                              ...
3772    im feeling stressed upcoming events drowning f...
5191    adress issues attempt reason may feel less thr...
5226    remember cammie couple months old looking swee...
5390    know feel feel absolutely terrified overwhelme...
860                     answered feeling rather skeptical
Name: Comment, Length: 4749, dtype: object

In [ ]:
x_test

1867    give times feel point friendship one cant both...
3988    im firm believer nothing makes woman feel much...
4516    feeling vulnerable one really close ever died ...
1397            closed eyes anger feeling disgusted touch
1669                                 feel like distracted
                              ...
642     feeling even less splendid nothing needed done...
1253                                        feel confused
3094    may pour half empty cup still making significa...
3733    really want challenge fun way everyone knock g...
3523    buy synthetic pearls feel need use elegant jew...
Name: Comment, Length: 1188, dtype: object

In [ ]:
df.shape

(5937, 2)

# **Text-Preprocessing/Feature Extraction/Vectorization**

**1.Bag of Words**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [ ]:
bow = CountVectorizer()

x_train_bow = bow.fit_transform(x_train)
x_test_bow = bow.transform(x_test)

In [ ]:
x_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 43040 stored elements and shape (4749, 7762)>

In [ ]:
x_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9714 stored elements and shape (1188, 7762)>

**2.TF-TDF Vectorizer**

In [ ]:
tfidf = TfidfVectorizer()

x_train_tfidf = tfidf.fit_transform(x_train)
x_test_tfidf = tfidf.transform(x_test)

In [ ]:
x_train_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43040 stored elements and shape (4749, 7762)>

In [ ]:
x_test_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9714 stored elements and shape (1188, 7762)>

# **Training a Model**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

1. naive bayes for bag of words

In [ ]:
nb_model = MultinomialNB()
nb_model.fit(x_train_bow,y_train)

MultinomialNB()

In [ ]:
nb_pred = nb_model.predict(x_test_bow)
print(accuracy_score(y_test,nb_pred))
print(classification_report(y_test,nb_pred))

0.8956228956228957
              precision    recall  f1-score   support

           0       0.89      0.92      0.91       416
           1       0.87      0.93      0.90       392
           2       0.93      0.83      0.88       380

    accuracy                           0.90      1188
   macro avg       0.90      0.89      0.89      1188
weighted avg       0.90      0.90      0.90      1188

2.naive bayes for TF-IDF Vectorizer

In [ ]:
nb_model_tf = MultinomialNB()
nb_model_tf.fit(x_train_tfidf,y_train)

MultinomialNB()

In [ ]:
nb_pred_tf = nb_model_tf.predict(x_test_tfidf)
print(accuracy_score(y_test,nb_pred_tf))
print(classification_report(y_test,nb_pred_tf))

0.9074074074074074
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       416
           1       0.88      0.94      0.91       392
           2       0.93      0.86      0.90       380

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188

1.SVM for Bag of Words

In [ ]:
svm_model = SVC(kernel='linear', C=1)
svm_model.fit(x_train_bow,y_train)

SVC(C=1, kernel='linear')

In [ ]:
svm_pred = svm_model.predict(x_test_bow)
print(accuracy_score(y_test,svm_pred))
print(classification_report(y_test,svm_pred))

0.9528619528619529
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       416
           1       0.94      0.95      0.95       392
           2       0.95      0.97      0.96       380

    accuracy                           0.95      1188
   macro avg       0.95      0.95      0.95      1188
weighted avg       0.95      0.95      0.95      1188

2. SVM for TF-IDF Vectorizer

In [ ]:
svm_model_tf = SVC(kernel='linear', C=1)
svm_model_tf.fit(x_train_tfidf,y_train)

SVC(C=1, kernel='linear')

In [ ]:
svm_pred_tf = svm_model_tf.predict(x_test_tfidf)
print(accuracy_score(y_test,svm_pred_tf))
print(classification_report(y_test,svm_pred_tf))

0.9452861952861953
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       416
           1       0.93      0.95      0.94       392
           2       0.95      0.97      0.96       380

    accuracy                           0.95      1188
   macro avg       0.95      0.95      0.95      1188
weighted avg       0.95      0.95      0.95      1188

1.Logistic Regression for Bag of words

In [ ]:
lg_model = LogisticRegression(max_iter=5000)
lg_model.fit(x_train_bow,y_train)

LogisticRegression(max_iter=5000)

In [ ]:
lg_pred = lg_model.predict(x_test_bow)
print(accuracy_score(y_test,lg_pred))
print(classification_report(y_test,lg_pred))

0.9511784511784511
              precision    recall  f1-score   support

           0       0.96      0.93      0.94       416
           1       0.94      0.96      0.95       392
           2       0.95      0.97      0.96       380

    accuracy                           0.95      1188
   macro avg       0.95      0.95      0.95      1188
weighted avg       0.95      0.95      0.95      1188

In [ ]:
lg_model_tf = LogisticRegression(max_iter=5000)
lg_model_tf.fit(x_train_tfidf,y_train)

LogisticRegression(max_iter=5000)

In [ ]:
lg_pred_tf = lg_model_tf.predict(x_test_tfidf)
print(accuracy_score(y_test,lg_pred_tf))
print(classification_report(y_test,lg_pred_tf))

0.9385521885521886
              precision    recall  f1-score   support

           0       0.95      0.91      0.93       416
           1       0.94      0.94      0.94       392
           2       0.92      0.97      0.95       380

    accuracy                           0.94      1188
   macro avg       0.94      0.94      0.94      1188
weighted avg       0.94      0.94      0.94      1188

In [ ]:
# import joblib
# joblib.dump(svm_model,'model.pkl')
# joblib.dump(bow,'vectorizer.pkl')

['vectorizer.pkl']

**Based on the accuracy scores, the SVM model with Bag of Words (BoW) vectorization performed the best with an accuracy of 0.9528.**