<a href="https://colab.research.google.com/github/PranavSarvaiyya/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
df = pd.read_csv('Emotion_classify_Data.csv')
df.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

# **Text-Cleaning**

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5937 entries, 0 to 5936
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Comment  5937 non-null   object
 1   Emotion  5937 non-null   object
dtypes: object(2)
memory usage: 92.9+ KB

In [55]:
df.describe()

                                                  Comment Emotion
count                                                5937    5937
unique                                               5934       3
top     i feel pretty tortured because i work a job an...   anger
freq                                                    2    2000

In [56]:
df.isnull().sum()

Comment    0
Emotion    0
dtype: int64

In [57]:
df['Emotion'].unique()

array(['fear', 'anger', 'joy'], dtype=object)

In [58]:
e_number = {}
i = 0
for e in df['Emotion'].unique():
    e_number[e] = i
    i += 1
df['Emotion'] = df['Emotion'].map(e_number)

In [59]:
df

                                                Comment  Emotion
0     i seriously hate one subject to death but now ...        0
1                    im so full of life i feel appalled        1
2     i sit here to write i start to dig out my feel...        0
3     ive been really angry with r and i feel like a...        2
4     i feel suspicious if there is no one outside l...        0
...                                                 ...      ...
5932                 i begun to feel distressed for you        0
5933  i left feeling annoyed and angry thinking that...        1
5934  i were to ever get married i d have everything...        2
5935  i feel reluctant in applying there because i w...        0
5936  i just wanted to apologize to you because i fe...        1

[5937 rows x 2 columns]

LowerCaseing

In [60]:
df['Comment'] = df['Comment'].apply(lambda x: x.lower())
df

                                                Comment  Emotion
0     i seriously hate one subject to death but now ...        0
1                    im so full of life i feel appalled        1
2     i sit here to write i start to dig out my feel...        0
3     ive been really angry with r and i feel like a...        2
4     i feel suspicious if there is no one outside l...        0
...                                                 ...      ...
5932                 i begun to feel distressed for you        0
5933  i left feeling annoyed and angry thinking that...        1
5934  i were to ever get married i d have everything...        2
5935  i feel reluctant in applying there because i w...        0
5936  i just wanted to apologize to you because i fe...        1

[5937 rows x 2 columns]

Remove Punctuations

In [61]:
import string
def remove_punctuation(txt):
  return txt.translate(str.maketrans('','',string.punctuation))
df['Comment'].apply(remove_punctuation)

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Numbers

In [62]:
def remove_number(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new
df['Comment'].apply(remove_number)

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove URL

In [63]:
import re
def remove_url(txt):
  new = "https?://\S+|www\.\S+"

  remove = re.sub(new,'',str(txt))
  return remove.strip()
df['Comment'] = df['Comment'].apply(remove_url)
df['Comment']

<>:3: SyntaxWarning: invalid escape sequence '\S'
<>:3: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_48766/959417279.py:3: SyntaxWarning: invalid escape sequence '\S'
  new = "https?://\S+|www\.\S+"

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove HTML Tags

In [64]:
def remove_tag(txt):
  new = r"<.*?>"

  remove = re.sub(new,'',str(txt))
  return remove.strip()
df['Comment'] = df['Comment'].apply(remove_tag)
df['Comment']

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Special Characters & Emojis

In [65]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new
df['Comment'] = df['Comment'].apply(remove_emojis)
df['Comment']

0       i seriously hate one subject to death but now ...
1                      im so full of life i feel appalled
2       i sit here to write i start to dig out my feel...
3       ive been really angry with r and i feel like a...
4       i feel suspicious if there is no one outside l...
                              ...
5932                   i begun to feel distressed for you
5933    i left feeling annoyed and angry thinking that...
5934    i were to ever get married i d have everything...
5935    i feel reluctant in applying there because i w...
5936    i just wanted to apologize to you because i fe...
Name: Comment, Length: 5937, dtype: object

Remove Stopwords

In [66]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
stopwords = set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [77]:
def remove_stopwords(txt):
  word = word_tokenize(txt)
  cleaned = []
  for i in word:
    if i not in stopwords:
      cleaned.append(i)
  return ' '.join(cleaned)
df['Comment'] = df['Comment'].apply(remove_stopwords)
df.loc[1]['Comment']

'im full life feel appalled'

Spelling check

In [78]:
from textblob import TextBlob
def correct_spell(txt):
  return str(TextBlob(txt).correct())

In [79]:
df

                                                Comment  Emotion
0     seriously hate one subject death feel reluctan...        0
1                            im full life feel appalled        1
2     sit write start dig feelings think afraid acce...        0
3     ive really angry r feel like idiot trusting fi...        2
4     feel suspicious one outside like rapture happe...        0
...                                                 ...      ...
5932                              begun feel distressed        0
5933  left feeling annoyed angry thinking center stu...        1
5934  ever get married everything ready offer got to...        2
5935  feel reluctant applying want able find company...        0
5936         wanted apologize feel like heartless bitch        1

[5937 rows x 2 columns]

# **Text-Preprocessing/Feature Extraction/Vectorization**